language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: eS+lKUqNsePdDNxBZWNrDx7Bzjh4rWeJwVS39I/k67vJu4L2/CfmauVDlQKVe3/ompSY2hYXoWyCqlKyOSv8RHp6CAoNz8/mtcRzxwJ8qzQgqRtm6ThMFGdaINnBIG0vs7lb6b7HZhl3j80JZ/Udj5c4q9nottR3HHP7ELqjvTbOO3/fzXQnESw/2SdYlQ0hv0TATHi8jxYcZ8LswBMhSLHMceVhd3PVCJPDryxyUBZ6Z7rUSLAxTtjv5aw1e0mAN4yKRwmcqXIev7E6P3oSU0S3EiloiEEufOWRc6xnJxvmbPQZOzEID98F2mVIXwAw0gLQMp5AJcvEntsecirMzDz7/ACk/8K8QW/q9fE61jtUdhNhMmA5VkSAXu/BTlDWXs4XuMQZIxt+iNigwv1tFRNfn82G/yzMPF7AEH1GHkeDou8dFaOVem7MKfBQ6J4g9yAh5/0WRignoNWw50ytGTLaMa91wjW1J99bypVb7FjAmV1gDtXONIwHeOJvbFyolDHjiJrUnz1MUIlGHPDosoCR556M7E4OYSzuKQvh0mljnz34RVldZ7MbVR2GtP8yz+LXl+GR9kjztiH6ko5+WYguI8jRU0wcfw5TEDvTGBrCIMclB1+YU3agNBsyrr/fGGAX3l2r1baKn5oi+n6p6QAabgEUc6v3G157FRXJxRE=
    on_pull_requests: false
before_install:
- curl -sL https://sentry.io/get-cli/ | bash
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B; bash sentry-release.sh
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
