language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: TfKGofyC6/bjADHE/EVI0POKigvq1vGy0sKN63ImMulKEf6k3cEgtiAhxu1z1VpOuti+dCgDVq68/T0nRd8f+cuxDUssJXiAyG99SE4lo1sHUwLP1WbB/QUwqL3mrN477JxZK+L0nIEaG7kq/XuMypsAPLwxaxL2gMAzw0Ce2qx8nZkqJUp3IcqonwlvjEL080NFksfPIRi3UElMDzAJcKg/Nt3tSj6Y3ulgf54oa1p6XzHhQ3To0KfzSJ41jLxHbP2EwJIeAb6INOKWbJySnAoVxVpKgt82M8JrKwGnujzzeVe78lh+23a/XU9S3/88molRkImr77Yaw6PDZjDyvDwLz1A/w/+h0o4JV4Obc6RbbsVT80mmh7KZJsNHfp6p7qat5fv3oD6BqLPQ0DS4aGbaXsr8ji9/7CI0XRMqQElxv0/apffqzemqPXPNEX3//YkALyOIYWTLOfKPKOeCN8+rfqKKqI3f2PCosbSqGeuGHOWY4U5M8TjXoDyWS17i0WOq81JroV+ELVIAOC8csK4T1W+oo2eJw4rIZz0rSi9EP+0cvqHNoOGuGmg4MYuTVqDHEQQncS3mPbVqLBqecldDtqHSMkCwf2LpIFFoZ58otewSIwuSOkazxuFG+xz9tGpFqSPXAayGnHfBImPQGdISuiAzJxnkQ+Lqmp/qWNY=
    on_pull_requests: false
before_install:
- curl -sL https://sentry.io/get-cli/ | bash
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B; bash sentry-release.sh
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
