language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: rw6RXnGd47G/eo2Sz79SV8vIqvGpZkdJruP/ZRDBJfnnniKeG/jIH3xMhIk78SKuAMt7b5rD56k3gewnWpBgc9o1O2h+n+Oe4SoMZ6auDfCP2K2XXXpdRKsMIZrmO9QOSlbbkp1JSyH5QkfGEQOzx37EDFfqVGlU3QRLANshBguZrvhvqsMPsYhXhG3zzlt6fGXffyi8GPfslr+VBZK3P86XGrWHYxumB1xneIPqBzUAvY589nCrJAw9Iq0HGa8vTe9qn8vxAuy4DS1cDQuqSeZTgh9hvtUCJlrVVMm7pJbZKN51Q8BfIR4bi5yoZoW3gcuwgNIEm1qaQec0JAv4jzl+G23NfpyjOxSHLq3xdMTuqUcT+vEptDVQSUq6HyvfIjvXCQqfKZXEDIO92JHgAw1QdO3KkyDk3OC1xZE+ukjQUgY93VhuW/M1Yd+S7GxGeU4Wdoq2sQuNVaDmG4U7qhgun7NS/ci06R+O/rVQLfr3dDg/dZZCQV0cANqizonY6hAEVK5MvWR+BFwCkN5954P6hnFCoUN7bDbD4ptMh45mTvn3Hd3cVCeAAvcnWgfRIsbx1U0Z9FPVtSy7PqM+lZJuofbTE06HJRXEGSiLQ7YoPNncN3K+lUwy6FKTQjCJ2+hM2ka49q6matDVWyZRU52MvGUKM3ZKMqskS6FLGMk=
before_install:
- curl -sL https://sentry.io/get-cli/ | bash
after_success:
- mvn jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B; bash sentry-release.sh
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
