language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: ZKBVT5MkDEEf3SlMuKp5dLGJdkoyoZR3z0NJ+o8FsEKzMdN1N184RJsx8BfRLS6pLadEVfEtTCnKIxH//4aoRMYm/EZOENPrwtbYwkaA8LvAPTmQtY2qO89KDVa+ZZkLCG4Pya5b7nt/AdvEIofw129wzdRwE8xjvCiewC58fq9WxHr4MFkT2PPqZ1uTo1BmvhTFtQ8TgO9XcSrN5zoweceOG9Ek1vwdEJyzswB6CaTainI+9rPP68JKRlTX/kYAnFLPFrawdKZx383hTCmgNR0nE77vmY4oRsKuI9hqZK/GPD1tThgy7XjgSMl8EPguzgG/3Xp9evoFFKWIH8cz/pbJ4dgu1ZCnYyoC/tSv/BIEdlse2A0qLXmTJ2aezC9cuURUsX5Vb1t3lwvdY7k8fzo6BZf7+6duFcCTxUkm8tzFA+i+ux2MMZ3sMKcEug29bw3Xni6KeZcEbZZus2wKH+9qvq15R8EoNCh6emYnLLtmly1tJWjjGpJsNS9a6TQ48Ezk6iM/LCZWwocozL7N925lOyxT/msbUlHwyS5LAH9wiQzAdDZGEqCAaBYiXwtYhdT96TtzKbClPcFsGTHU7YQjhzhE7tmQYx0ODvHmcSg+4MZDcH3I7iv2lleuDTO14wOShR5Wy0UrLWkZVQiApq3ZmuV2cE8DwmndfYRMeZM=
before_install:
- curl -sL https://sentry.io/get-cli/ | bash
after_success:
- mvn jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B; bash sentry-release.sh
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
