package com.shepherdjerred.capstone.engine.engine.graphics.texture;

public enum TextureName {
  FROST_WALL,
  FIRE_WIZARD_FRONT,
  TERRAIN,
  MAIN_MENU_BUTTON,
  MAIN_MENU_BUTTON_HOVERED,
  MAIN_MENU_BUTTON_CLICKED,
  PURPLE_MOUNTAINS,
  PURPLE_MOUNTAINS_A,
  PURPLE_MOUNTAINS_B,
  PURPLE_MOUNTAINS_C,
  PURPLE_MOUNTAINS_D,
  PURPLE_MOUNTAINS_E,
  RED_PLAINS,
  TEAM_LOGO,
  GAME_LOGO,
  UNKNOWN
}
